### ISSUE TITLE
Plugin not working after latest Firefox Update (Firefox 87.0)

### ISSUE THREAD

**Issue by aekst** [codebicycle/videospeed#136] opened 2021-03-26 16:28 UTC

**Comment by KamiOh** [comment] 2021-03-26 18:03
Same problem for here. 
Sometimes work, sometimes not.

**Comment by jonoave** [comment] 2021-03-26 23:45
Experiencing the same thing. The speed controller is no longer visible. Restarted firefox already. 

More details:

This was on Pop Os. 20.10.
Update: This controller is alsn not visible on Netflix -(I usually like to watch my shows at 1.1-1.2x speed).

**Comment by IanBlakeley** [comment] 2021-03-27 05:28
Seeing same thing in FF for Linux V87 with YouTube, however, if I left click and select a video to play from those in right hand tab the controls are then visible. Again if open in a New Tab or new window with a right click then the controls are not available

**Comment by pederbe** [comment] 2021-03-27 09:51
I have the same problem. Since today the controller never shows up in Firefox 87.0 (Win 10).

**Comment by aekst** [comment] 2021-03-28 00:36
I should correct my self. The controller is still working, I can still do 
```
S - decrease playback speed.
D - increase playback speed.
R - reset playback speed.
Z - rewind video by 10 seconds.
X - advance video by 10 seconds.
V - show/hide controller.
```
But the controller is not visible anymore.

**Comment by rsyh93** [comment] 2021-03-28 06:41
Same problem here. Shortcuts work, but the controller overlay is not visible. When Inspecting, it looks like .vsc-nosource is on the controller div. Disabling the style or removing the class makes the controller appear again.

EDIT:
Duplicate of #127

**Comment by lamyergeier** [comment] 2021-03-29 08:42
same problem on Ubuntu 20.04, Firefox 87

**Comment by FlorianAliasJoe** [comment] 2021-03-29 10:56
Same here : shortcuts work but the controller is not visible.

**Comment by avh03** [comment] 2021-03-29 21:08
> But the controller is not visible anymore.

Same here (at least on youtube): Video Speed Controller 0.6.3.2, MacOS 10.15.7, FF 87.0 (64 bit)

**Comment by lexicalunit** [comment] 2021-03-29 22:29
The controller still works via keyboard shortcuts, but is no longer visible.

- Video Speed Controller Version 0.6.3.2
- Firefox 87.0 (64-bit)
- macOS 10.16

**Comment by v0dan** [comment] 2021-03-30 14:31
Controller works but its not visible on some websites and wont always save preferred speed (for example Youtube sometimes visible sometimes not and speed sometimes resets to 1.0).
Checking "Settings>Force last saved speed" fixed it for me.

**Comment by Slayde-Silver** [comment] 2021-03-30 19:12
I found a way to bring the controller back from the youtube video that I am watching. If the controller is not visible on the video it still works. However, if you want it to be visible on youtube at least, you change the video resolution on that video and then you can change it back to whatever, and the controller will appear again. I think what is happening is that the latest Firefox update patch that changed how videos are being loaded has changed how the visuals appear for the video. And the controller is appearing after the actual video. Once you change the resolution it refreshes just the playback engine not the whole webpage.

**Comment by wppoland** [comment] 2021-03-31 12:44
> I found a way to bring the controller back from the youtube video that I am watching. If the controller is not visible on the video it still works. However, if you want it to be visible on youtube at least, you change the video resolution on that video and then you can change it back to whatever, and the controller will appear again. I think what is happening is that the latest Firefox update patch that changed how videos are being loaded has changed how the visuals appear for the video. And the controller is appearing after the actual video. Once you change the resolution it refreshes just the playback engine not the whole webpage.

It also doesn't help always :/

I'm looking forward to seeing an update!

**Comment by nschulzke** [comment] 2021-03-31 19:07
This pull request fixes it for me: https://github.com/codebicycle/videospeed/pull/134

If you need a temporary fix while it's approved, disable the add-on, clone BreezeZin's branch, and follow the instructions here to install an add-on from source: https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Your_first_WebExtension#installing

**Comment by gl1000007** [comment] 2021-04-01 10:21
Same problem for me, for sites like YouTube, Netflix, Facebook.
Plugin version 0.6.3.2 on Firefox 87.0 64 Bit on Windows 10.
Controller won't show, but keyboard shortcuts work.
Pressing V to show controller does not work.
'Hide controller by default' option is unchecked.
Controller opacity is 0.3 (I think it's the default value).
Uninstalling and reinstalling does not work.

**Comment by codebicycle** [comment] 2021-04-06 16:42
The new version 0.6.3.3 should fix the controller not showing in Firefox 87.0

**Comment by gl1000007** [comment] 2021-04-06 16:46
YES!!!!! 0.6.3.3 WORKS!
Tried it on YouTube and Netflix.
Thanks @codebicycle

**Comment by SoMuchForSubtlety** [comment] 2021-04-06 16:48
Works for me on both windows and linux. 👍

**Comment by pintassilgo** [comment] 2021-04-06 20:35
Fixed in Firefox 88+:
https://bugzilla.mozilla.org/show_bug.cgi?id=1701276

**Closed as completed** 2021-04-10 01:07 UTC
