### ISSUE TITLE
Overlay gets/is missing on Youtube in Firefox 87

### ISSUE THREAD

**Issue by scorpion421** [codebicycle/videospeed#127] opened 2021-02-23 19:54 UTC
Just reporting, that the overlay will get missing on some sites for users with Firefox 87 b1. For example: Youtube.
Other sites like 9GAG are fine. Don't know what happens here. Shortcuts are working fine - even if the overlay is not showing up.
Reverted to Firefox 86 (stable channel) and the overlay came back as it should.
Maybe useful for you or other users to know why this might happen.

Edit: Just in addition for people maybe asking how to downgrade: firefox.exe -allow-downgrade

**Comment by fbrminsk** [comment] 2021-02-25 11:33
I confirm. Firefox 87 b2 - the indicator is missing though playback control is preserved.

**Comment by veremenko-y** [comment] 2021-02-28 16:33
87b3 was broken yesterday, but seems to be fixed now (on the same version)

**Comment by BubiBalboa** [comment] 2021-03-04 01:11
Still broken for me as of FF87.0b5

**Comment by richardhartme** [comment] 2021-03-05 21:28
Not showing in FF87.0b6 but does show in the latest nightly build FF88.0a1 (2021-03-05).

**Comment by cayhorstmann** [comment] 2021-03-22 10:24
I have the same problem with Pathable (a tool for online conferences). Seems like a plain `<video>` element, but no visible controls. Keyboard shortcuts work.

**Comment by olliebean** [comment] 2021-03-24 12:16
Confirmed the overlay is not showing on YouTube (I haven't tested other sites) in the release version of Firefox 87. The keyboard shortcuts are working as expected.

**Comment by 0xC0FFEE** [comment] 2021-03-24 19:13
Can also confirm this issue.

However it seems, that sometimes the overlay is visible on YouTube and sometimes it isn't. If I figure out a pattern I'll report back.

Edit: FWICT it seems to be independent of the video being watched. It seems kinda random to me. However it is quite rare, that the overlay is visible on YouTube. On all other websites I use the overlay is always visible.

**Comment by Notare** [comment] 2021-03-26 14:54
> 
> 
> Can also confirm this issue.
> 
> However it seems, that sometimes the overlay is visible on YouTube and sometimes it isn't. If I figure out a pattern I'll report back.
> 
> Edit: FWICT it seems to be independent of the video being watched. It seems kinda random to me. However it is quite rare, that the overlay is visible on YouTube. On all other websites I use the overlay is always visible.

Also random for me, some videos has the overlay, some don't, this only happens on YouTube.

**Comment by scorpion421** [comment] 2021-03-26 16:43
You can force to show it by PiP-Mode and Youtube Miniplayer using the same time. Dunno the exact steps - have to be home for reproducing. I also thought, maybe the z-index is the issue and tinkered around. But after seeing your value, it can't be the issue. Maybe Firefox is buggy and prioritizes commands like --ytd-z-index-report-form-overlay and so on. No problem on Chrome or Chromium forks. 

Well, seems there is one commit to have to get included. 2 days old already:
https://github.com/codebicycle/videospeed/pull/134

**Comment by LiderKonmils** [comment] 2021-03-28 22:26
Other informations that could be usefull: 
-Hidden on Youtube
-Hidden on Netflix
-Showed on Twitch (Replays and lives)
-Hidden on Twitter and Facebook (even when enabled)
-Showed on Dailymotion.
-Still working with the keys (S,D) on all thoses websites.

I don't know if thoses informations can help in anyway, but i still post them.

**Comment by scorpion421** [comment] 2021-03-28 22:42
I edited the file like in the last pull request and works. As soon as codebicycle merges it and get a .xpi compiled and signed for an update, the problem is solved. I close the thread, because the problem will get solved as soon as the pull request will be merged.
Edit: Closing it isn't the perfect option I think, since the issue probably vanishes for all other users... Just wait for the merge :)

**Comment by codebicycle** [comment] 2021-04-06 16:44
The new version 0.6.3.3 should fix the controller not showing in Firefox 87.0

**Closed as completed** 2021-04-06 16:58 UTC
