### ISSUE TITLE
Controller not showing when you open video in a new tab

### ISSUE THREAD

**Issue by adachoinw** [codebicycle/videospeed#135] opened 2021-03-25 03:02 UTC
Pressing V doesn't work.
It only shows when you click on the next video on the right side playlist.

**Comment by h-h-h-h** [comment] 2021-03-25 11:33
The controls are also not showing up for me over YouTube videos at first. Only after navigating to another video.

It might be relevant in this context, that YouTube uses the `pushState()` API.

**Comment by scorpion421** [comment] 2021-03-28 22:45
Duplicate of #127

**Comment by codebicycle** [comment] 2021-04-06 16:42
The new version 0.6.3.3 should fix the controller not showing in Firefox 87.0

**Closed as completed** 2021-04-06 17:34 UTC
